products:
  - 
    name: 'Account'
    icon: 'phone'
    icon_colour: 'blue'
    path: 'account'
    dropdown: true
  - 
    name: 'Concepts'
    icon: 'message'
    icon_colour: 'green'
    path: 'concepts'
    dropdown: true
